import Dropdown from "./Dropdown";
import React from "react";

export default function Amenities({ formValues, setFormValues }) {
    const optionsValuesAmenities = [
        "kitchen",
        "wifi",
        "essentials",
        "heating",
        "hair_dryer",
        "long_term_stays_allowed",
        "hangers",
        "washer",
        "hot_water",
        "smoke_alarm",
        "iron",
        "dishes_and_silverware",
        "refrigerator",
        "cooking_basics",
        "shampoo",
        "bed_linens",
        "coffee_maker",
        "stove",
        "oven",
        "tv",
        "dishwasher",
        "free_street_parking",
        "dedicated_workspace",
        "first_aid_kit",
        "microwave",
        "elevator",
        "extra_pillows_and_blankets",
        "fire_extinguisher",
        "hot_water_kettle",
        "private_entrance",
        "luggage_dropoff_allowed",
        "host_greets_you",
        "carbon_monoxide_alarm",
        "roomdarkening_shades",
        "bathtub",
        "dining_table",
        "cleaning_products",
        "shower_gel",
        "wine_glasses",
        "freezer",
        "baking_sheet",
        "toaster",
        "drying_rack_for_clothing",
        "body_soap",
        "lock_on_bedroom_door",
        "dryer",
        "free_parking_on_premises",
        "single_level_home",
        "patio_or_balcony",
        "tv_with_standard_cable",
        "private_patio_or_balcony",
        "central_heating",
        "crib",
        "high_chair",
        "lockbox",
        "self_checkin",
        "paid_parking_off_premises",
        "cable_tv",
        "pets_allowed",
        "portable_fans",
        "outdoor_dining_area",
        "backyard",
        "outdoor_furniture",
        "laundromat_nearby",
        "pack_u2019n_playtravel_crib",
        "childrenu2019s_books_and_toys",
        "ethernet_connection",
        "coffee",
        "smoking_allowed",
        "free_washer_u2013_in_unit",
        "clothing_storage_wardrobe",
        "books_and_reading_material",
        "bbq_grill",
        "security_cameras_on_property",
        "clothing_storage",
        "conditioner",
        "paid_parking_on_premises",
        "childrenu2019s_dinnerware",
        "paid_street_parking_off_premises",
        "board_games",
        "breakfast",
        "blender",
        "air_conditioning",
        "free_washer_u2013_in_building",
        "mini_fridge",
        "smart_lock",
        "baby_bath",
        "electric_stove",
        "indoor_fireplace",
        "barbecue_utensils",
        "ev_charger",
        "outlet_covers",
        "shared_patio_or_balcony",
        "safe",
        "window_guards",
        "stainless_steel_oven",
        "clothing_storage_closet",
        "waterfront",
        "bikes",
        "courtyard_view",
    ]
    const optionsLabelsAmenities = [
        "kitchen",
        "wifi",
        "essentials",
        "heating",
        "hair dryer",
        "long term stays allowed",
        "hangers",
        "washer",
        "hot water",
        "smoke alarm",
        "iron",
        "dishes and silverware",
        "refrigerator",
        "cooking basics",
        "shampoo",
        "bed linens",
        "coffee maker",
        "stove",
        "oven",
        "tv",
        "dishwasher",
        "free street parking",
        "dedicated workspace",
        "first aid kit",
        "microwave",
        "elevator",
        "extra pillows and blankets",
        "fire extinguisher",
        "hot water kettle",
        "private entrance",
        "luggage dropoff allowed",
        "host greets you",
        "carbon monoxide alarm",
        "roomdarkening shades",
        "bathtub",
        "dining table",
        "cleaning products",
        "shower gel",
        "wine glasses",
        "freezer",
        "baking sheet",
        "toaster",
        "drying rack for clothing",
        "body soap",
        "lock on bedroom door",
        "dryer",
        "free parking on premises",
        "single level home",
        "patio or balcony",
        "tv with standard_cable",
        "private patio or balcony",
        "central heating",
        "crib",
        "high chair",
        "lockbox",
        "self checkin",
        "paid parking off premises",
        "cable tv",
        "pets allowed",
        "portable fans",
        "outdoor dining area",
        "backyard",
        "outdoor furniture",
        "laundromat nearby",
        "playtravel crib",
        "books and toys",
        "ethernet connection",
        "coffee",
        "smoking allowed",
        "free washer in unit",
        "clothing storage wardrobe",
        "books and reading material",
        "bbq grill",
        "security cameras on property",
        "clothing storage",
        "conditioner",
        "paid parking on premises",
        "children dinnerware",
        "paid street parking off premises",
        "board games",
        "breakfast",
        "blender",
        "air conditioning",
        "free washer in building",
        "mini fridge",
        "smart lock",
        "baby bath",
        "electric stove",
        "indoor fireplace",
        "barbecue utensils",
        "ev charger",
        "outlet covers",
        "shared patio or balcony",
        "safe",
        "window guards",
        "stainless steel oven",
        "clothing storage closet",
        "waterfront",
        "bikes",
        "courtyard view",
    ]
    const optionsAmenities = optionsLabelsAmenities.map((label, index) =>
    ({ label: label, value: optionsValuesAmenities[index] }));

    return (
        <div className="dropdown">
            <h2>Amenities</h2>
            <Dropdown
            name="Amenities of the property: "
            options={optionsAmenities}
            onChange={amenities => {setFormValues({ ...formValues, amenities })}}
            isMulti={true}
            useLabel={true}
            />
        </div>
    )
}